ARG MY_PHP_VERSION
FROM madsem/phpdock:${MY_PHP_VERSION}

# Install additional extensions, packages etc.
#RUN install-php-extensions csv decimal

# Customize PHP config
#COPY php.ini /usr/local/etc/php/php.ini

WORKDIR /var/www/html
