#!/usr/bin/env bash

DOCKER_ACC=madsem
DOCKER_REPO=phpdock
TAG_SUFFIX=latest
DOCKER=$(which docker)

for PATH in ./*; do
    [ -d "${PATH}" ] || continue # if not a directory, skip
    IMG=${PATH#*/}
    TAG=$IMG-$TAG_SUFFIX
    
    # build & tag image
    $DOCKER build -t $DOCKER_ACC/$DOCKER_REPO:$TAG $IMG

    # push latest version to docker hub
    $DOCKER push $DOCKER_ACC/$DOCKER_REPO:$TAG
done

